#!/bin/bash

doc=$"/home/$USER/Documents/bandit"

grep "lvl "$1"" "$doc/overthewire_pass.txt" | cut -d" " -f3 > "$doc/pass.txt"

sshpass -vf  "$doc/pass.txt" ssh bandit"$1"@bandit.labs.overthewire.org -p2220


