#!/usr/bin/bash

#download and unzip repository
wget https://github.com/im1gr4nt/bandit_pass/archive/refs/heads/main.zip 
unzip main.zip
cd bandit_pass-main

#define doc variable
doc=$"/home/$USER/Documents" 

#check if user has Documents directory and place there 2 files
if [[ ! -d $doc ]]; then
	mkdir $doc 
else
	:
fi

mkdir "$doc/bandit"  
mv overthewire_pass.txt "$doc/bandit" 

#delete all unnecessary files
cd ..
rm -rf bandit_pass-main
