#!/usr/bin/bash

#download and unzip repository
wget https://github.com/im1gr4nt/bandit_pass/archive/refs/heads/master.zip
unzip master.zip
cd bandit_pass-master

#define doc variable
doc=$($HOME/Documents)
bin=$($HOME/bin)

#check if Documents directory exists and place there 2 files
if [[ ! -d $doc ]]; then
	mkdir $doc 
else
	:
fi

mkdir "$doc/bandit"  
mv otw_pass.txt "$doc/bandit" 
chmod u+x otw_pass.txt

#check if bin directory exists and place there bandit file
if [[ ! -d $bin ]]; then
	mkdir $bin 
else
	:
fi

mv bandit "$bin" 

#check if path has home bin dir inserted, add if not
if [[ echo $PATH | grep "$HOME/bin" ]]; then
	:
else
	export PATH="$HOME/bin:$PATH"

#delete all unnecessary files
cd ..
rm -rf bandit_pass-master master.zip
